---
title: "What makes an epidemic a disaster: the future of epidemics within the EM-DAT International Disaster Database"
subtitle: "BMC Public Health" 
year: 2025
date: "2025-01-03"
doi: "10.1186/s12889-024-21026-2"
author: 
 - name: Margo Tonnelier
 - name: Damien Delforge
 - name: Regina Below
 - name: Juan Armando Torres Munguía
   orcid: 0000-0003-3432-6941
 - name: Claude Saegerman
 - name: Valentin Wathelet
 - name: Joris A. F. van Loenhout
 - name: Niko Speybroeck
categories:
 - disease outbreaks
 - epidemics
 - pandemics
 - disasters
 - open data
links:
- icon: file-pdf
  icon_pack: fas
  name: PDF
  url: https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-024-21026-2
format: 
  html: 
    page-layout: article
---

### Abstract 
<p> Reporting on and monitoring epidemics is a public health priority. Several initiatives and platforms provide epidemiological data, such as the EM-DAT International Disaster Database, which has 1525 epidemics and their impact reported since 1900, including 892 epidemics between 2000 and 2023. However, EM-DAT has inconsistent coverage and deficiencies regarding the systematic monitoring of epidemics data due to the lack of a standardized methodology to define what will be included under an epidemic disaster.
We conducted a sequential study that included an online survey of experts in infectious diseases, public health emergencies, and related data, followed by committee discussions with disaster experts. This approach aimed to identify appropriate definitions and entry criteria for archiving disease outbreak events.
The survey had 21 respondents from universities and international organizations, with experts primarily specialized in infectious disease surveillance. Experts agreed that epidemics should be considered as disasters. Experts cited challenges in defining epidemic thresholds. However, they proposed pathogen-based criteria and agreed that disruption to society, especially to the healthcare system, serves as a determinant of epidemic disasters. The experts favored deaths and confirmed cases as key indicators, alongside suggestions on refining EM-DAT's entry criteria and improving epidemic impact assessment.
This article offers valuable insights into epidemic disasters, a topic previously underdefined in the literature, thereby enhancing understanding for policymakers and public health professionals. 

### Citation
<p><b>Tonnelier, Margo; Delforge, Damien; Below, Regina; Munguía, Juan Armando Torres; Saegerman, Claude; Wathelet, Valentin; van Loenhout, Joris A. F.; Speybroeck, Niko</b> (2025). What makes an epidemic a disaster: the future of epidemics within the EM-DAT International Disaster Database. <i>BMC Public Health</i>, 25 (1). DOI: <a href="10.1186/s12889-024-21026-2" target="_blank">10.1186/s12889-024-21026-2</a></p>

```{=html}

  <div class="container text-center mt-4" >
  <a href="cite.bib" class="btn custom-btn mt-1" style="border:1px solid #153268; background-color: #153268; margin-top: 5px;" download>
    <i class="fas fa-cloud-arrow-down"></i> Download .bib file <br> (compatible with LaTeX)
  </a>

```
